name: Mr. Ledbetter
favicon: null
layout_spectrum: 0.50232
typography_spectrum: 0.4428729044739157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.16404408472590148
  saturation: 0.2863245764747262
  rhythmicContrast: 0.5071143640670925
purpose: []
